repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.14.1
    hooks:
      # Run the linter.
      - id: ruff
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude_types: [html, svg]
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        args: ["--maxkb=1000", "--enforce-all"]
        exclude: "cosmica/visualization/assets/ne_50m_admin_0_countries_lakes.shp"
      - id: check-merge-conflict
      - id: check-symlinks
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: check-shebang-scripts-are-executable
      - id: check-executables-have-shebangs
      - id: check-illegal-windows-names
      - id: fix-byte-order-marker
      - id: forbid-submodules
      - id: no-commit-to-branch

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.9.5
    hooks:
      # Update the uv lockfile
      - id: uv-lock
