site_name: COSMICA Documentation
site_url: https://cosmica.ut-issl.com/
theme:
  name: material
  icon:
    logo: material/satellite-variant
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: yellow
      accent: yellow

      # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: yellow
      accent: yellow

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: yellow
      accent: yellow
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
plugins:
  - search
  # - gen-files:
  #     scripts:
  #       - scripts/gen_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_if_no_docstring: true
            unwrap_annotated: true
            show_root_heading: true
            inherited_members: true
            separate_signature: true
            merge_init_into_class: true
            signature_crossrefs: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_signature_annotations: true
            docstring_section_style: spacy
            preload_modules:
              - pymap3d.aer
            extensions:
              - griffe_typingdoc
repo_url: https://github.com/ut-issl/cosmica
repo_name: ut-issl/cosmica
markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
# nav:
#   - Home: index.md
#   - API Reference: reference/
#   - For Developers:
#       - Setting up development environment: developers/setup.md
#       - Development rules and tips: developers/tips.md
#       - Releasing COSMICA: developers/releasing.md
# extra:
#   version:
#     provider: mike
