"""Generate the documentation home page consumed by Zensical.

The API reference pages are generated by Zensical's `api-autonav` plugin.
"""

from pathlib import Path

PROJECT_ROOT = Path(__file__).parents[1]
DOCS_DIR = PROJECT_ROOT / "docs"
GENERATED_NOTICE = "<!-- Generated by scripts/gen_index_page.py. Do not edit. -->\n\n"


def gen_index_page() -> None:
    """Generate the documentation home page from the project README."""
    readme_content = (PROJECT_ROOT / "README.md").read_text(encoding="utf-8")
    index_content = adjust_documentation_paths(readme_content)
    (DOCS_DIR / "index.md").write_text(
        GENERATED_NOTICE + index_content,
        encoding="utf-8",
    )


def adjust_documentation_paths(content: str) -> str:
    """Adjust README paths to be relative to the documentation root."""
    return content.replace("](docs/", "](")


if __name__ == "__main__":
    gen_index_page()
