"""Generate physical Markdown pages consumed by Zensical."""

from collections.abc import Iterator
from pathlib import Path
from shutil import rmtree

PROJECT_ROOT = Path(__file__).parents[1]
DOCS_DIR = PROJECT_ROOT / "docs"
REFERENCE_DIR = DOCS_DIR / "reference"
GENERATED_NOTICE = "<!-- Generated by scripts/gen_ref_pages.py. Do not edit. -->\n\n"


def gen_index_page() -> None:
    """Generate the documentation home page from the project README."""
    readme_content = (PROJECT_ROOT / "README.md").read_text(encoding="utf-8")
    index_content = adjust_documentation_paths(readme_content)
    (DOCS_DIR / "index.md").write_text(
        GENERATED_NOTICE + index_content,
        encoding="utf-8",
    )


def adjust_documentation_paths(content: str) -> str:
    """Adjust README paths to be relative to the documentation root."""
    return content.replace("(docs/", "(")


def iter_reference_pages() -> Iterator[tuple[Path, str]]:
    """Yield each generated reference path and its Python identifier."""
    src_dir = PROJECT_ROOT / "src"
    package_root = src_dir / "cosmica"

    for path in sorted(package_root.rglob("*.py")):
        module_path = path.relative_to(src_dir).with_suffix("")
        doc_path = path.relative_to(src_dir).with_suffix(".md")
        parts = module_path.parts

        match parts[-1]:
            case "__init__":
                parts = parts[:-1]
                if any(part.startswith("_") for part in parts):
                    continue
                doc_path = doc_path.with_name("index.md")
            case "__main__":
                continue
            case _ if any(part.startswith("_") for part in parts):
                continue

        yield REFERENCE_DIR / doc_path, ".".join(parts)


def gen_ref_pages() -> None:
    """Generate one mkdocstrings page for each public Python module."""
    rmtree(REFERENCE_DIR, ignore_errors=True)

    for doc_path, identifier in iter_reference_pages():
        doc_path.parent.mkdir(parents=True, exist_ok=True)
        doc_path.write_text(
            f"{GENERATED_NOTICE}::: {identifier}\n",
            encoding="utf-8",
        )


def main() -> None:
    """Generate all documentation derived from repository sources."""
    gen_index_page()
    gen_ref_pages()


if __name__ == "__main__":
    main()
